"""Database-backed vector similarity retrieval using pgvector."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TypedDict
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import Chunk, ChunkEmbedding, Document
from app.retrieval.filters import build_document_filter_clauses


class RetrievalRecord(TypedDict):
    """Single retrieval result payload returned by vector similarity search."""

    chunk_id: UUID
    chunk_text: str
    document_id: UUID
    score: float


def similarity_search(
    session: Session,
    query_embedding: Sequence[float],
    top_k: int = 5,
    metadata_filters: Mapping[str, str] | None = None,
) -> list[RetrievalRecord]:
    """
    Search chunk embeddings by cosine similarity and return top-k chunks.

    Args:
        session: Open SQLAlchemy session.
        query_embedding: Query vector generated by the embedding service.
        top_k: Maximum number of rows to return.
        metadata_filters: Optional metadata filter conditions.

    Returns:
        Retrieval-ready rows with chunk/document IDs, text, and similarity score.
    """
    if top_k < 1:
        raise ValueError("top_k must be >= 1")
    if not query_embedding:
        return []

    distance_expr = ChunkEmbedding.embedding.cosine_distance(list(query_embedding))
    score_expr = (1 - distance_expr).label("score")

    stmt = (
        select(
            Chunk.id.label("chunk_id"),
            Chunk.text.label("chunk_text"),
            Chunk.document_id.label("document_id"),
            score_expr,
        )
        .select_from(ChunkEmbedding)
        .join(Chunk, Chunk.id == ChunkEmbedding.chunk_id)
        .join(Document, Document.id == Chunk.document_id)
        .order_by(distance_expr.asc())
        .limit(top_k)
    )

    filter_clauses = build_document_filter_clauses(metadata_filters)
    if filter_clauses:
        stmt = stmt.where(*filter_clauses)

    rows = session.execute(stmt).all()
    return [
        {
            "chunk_id": row.chunk_id,
            "chunk_text": row.chunk_text,
            "document_id": row.document_id,
            "score": float(row.score),
        }
        for row in rows
    ]
